# Generated by Django 4.1.13 on 2025-11-01 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата'), ('transfer', 'Переказ')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'db_table': 'transaction_categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('currency_preference', models.CharField(default='UAH', max_length=3)),
                ('timezone', models.CharField(default='Europe/Kiev', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('monobank', 'Monobank'), ('pumb', 'ПУМБ'), ('binance', 'Binance'), ('bybit', 'Bybit'), ('okx', 'OKX'), ('manual', 'Вручну')], max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата'), ('transfer', 'Переказ'), ('trade', 'Торгівля'), ('deposit', 'Депозит'), ('withdrawal', 'Виведення')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('counterparty', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transactioncategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Успішно'), ('partial', 'Частково'), ('failed', 'Помилка')], max_length=20)),
                ('transactions_added', models.IntegerField(default=0)),
                ('transactions_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('income', 'Прогноз доходів'), ('expense', 'Прогноз витрат'), ('balance', 'Прогноз балансу'), ('crypto', 'Прогноз крипто')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0-100', max_digits=5)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Forecast',
                'verbose_name_plural': 'Financial Forecasts',
                'db_table': 'financial_forecasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_name', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('okx', 'OKX')], max_length=50)),
                ('api_key', finance.models.EncryptedField()),
                ('api_secret', finance.models.EncryptedField()),
                ('api_passphrase', finance.models.EncryptedField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активне'), ('inactive', 'Неактивне'), ('error', 'Помилка')], default='active', max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crypto Exchange',
                'verbose_name_plural': 'Crypto Exchanges',
                'db_table': 'crypto_exchanges',
            },
        ),
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('monobank', 'Monobank'), ('pumb', 'ПУМБ')], max_length=50)),
                ('access_token', finance.models.EncryptedField()),
                ('refresh_token', finance.models.EncryptedField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активне'), ('inactive', 'Неактивне'), ('error', 'Помилка')], default='active', max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Connection',
                'verbose_name_plural': 'Bank Connections',
                'db_table': 'bank_connections',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_date'], name='transaction_user_id_062bde_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source', 'source_id'], name='transaction_source_58e248_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('source', 'source_id')},
        ),
        migrations.AddIndex(
            model_name='financialforecast',
            index=models.Index(fields=['user', 'period_start', 'period_end'], name='financial_f_user_id_f7221c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptoexchange',
            unique_together={('user', 'exchange_name')},
        ),
        migrations.AlterUniqueTogether(
            name='bankconnection',
            unique_together={('user', 'bank_name')},
        ),
    ]
